img_ind: 38
#step_str: '012345678'
step_str: '0'
# thread_method: 'queue'
thread_method: 'concurrent'
# pic_thread_method: 'queue'
pic_thread_method: 'concurrent'
do_mode: 'do_qt'
# do_mode: 'do_dev_folder'
# do_mode: 'do_dev_pic'
docx_img_format: 'jpeg'
#docx_img_format: 'png'
folder_name: 'Afterlift 002'
area_folder_names:
#   - 'Afterlift 001'
# default_dpi: 300
# default_dpi: 200
default_dpi: 150
# default_dpi: 96
WLB_ext_px_dic:
  Comic: 4,15,18
  Manhua: 12,50,25
lettering:
#   global_font_size: 20
#   global_font_size: 28
  global_font_size: 30
  global_font_name: '微软雅黑'
#   global_font_name: '思源黑体'
#   global_font_name: '方正兰亭黑'
#  global_rec_font_name: '方正粗宋'
  global_rec_font_name:
  global_spacing:
#   global_spacing: 8
  check_len: 40
#browser: 'Safari'
browser: 'Google Chrome'
thumb_size: 240
window_size: 1200,800
WBLDN_padding: 40,50,30,30,30
# WBLDN_padding: 30,50,90,90,90
# WBLDN_padding: 90,90,90,90,90
# WBLDN_padding: 60,120,120,120,120
font_size_range_dic:
  default: '30~30'
  'ffffff-000000': '30~30'
font_size_rarange: '0.65~1.25'
bold_thres_dic:
  default: 1.15
#   'ffffff-000000': 1.2
#   '3948a5-ffffff': 1.5
stem_level: 3
font_dic:
  微软雅黑: 'msyh.ttc'
  方正兰亭黑: '方正兰亭黑_GBK.ttf'
  方正粗宋: '方正粗宋_GBK.ttf'
  水木明淙: '水木明淙.TTF'
  方正诗甜宋: '方正诗甜宋 简 Medium.TTF'
  方正雪炜锐黑: '方正雪炜锐黑 简.TTF'
  思源黑体: 'NotoSansHans-Regular.otf'
chatgpt:
  # 是否允许控制浏览器
  do_automate: true
#   do_automate: false
  sleep_minute: 3
  gpt_line_max: 40
  gpt_char_max: 1500
long_pic:
#  single_width_min: 1900
  single_width_min: 2000
#   single_width_min: 3200
  group_len: 4
#  group_len: 6
frame_settings:
  frame_color:
#   frame_color: '000000'
#  frame_color: 'ffffff'
  min_frame_length: 3
  edge_size: 10
  edge_ratio: 0.135
  # 框架宽度
  grid_width_min: 100
  # 框架高度
  grid_height_min: 100
  # 考虑无背景无框架的画格
  #max_white_ratio: 0.5
  max_white_ratio: 0.9
  # 是否根据漫画画格添加边线
  do_add_frame: true
#  do_add_frame: false
  frame_level: 3
  frame_thres: 0.9995
  min_width: 60
  min_outline_len: 40
  gaps: [15, 6, 8, 8]
#  gaps: 0
  # 是否检查由多种颜色构成漫画画格框架
  #check_2nd_color: true
  check_2nd_color: false
  # 是否使用多种颜色检测漫画画格
  #check_more_frame_color: true
  check_more_frame_color: false
#  y_1st: true
  y_1st: false
  fully_framed: true
#  fully_framed: false
bubble_condition:
  area_range: '80~1000000'
  perimeter_range: '8~40000'
  thickness_range: '3~4000'
  br_w_range: '120~6000'
  br_h_range: '30~6000'
  br_wh_range: '20~6000'
  br_wnh_range: '40~6000'
  br_w_rarange: '0.003~1'
  br_h_rarange: '0.003~1'
  br_rarange: '0.02~1.1'
#   br_rarange: '0.9~1.1' #矩形
#  br_rarange: '0.02~0.9' #非矩形
  br_w_prange: '0~1'
#  br_w_prange: '0.4~1'
  br_h_prange: '0~1'
#   br_h_prange: '0~0.5'
  portion_rarange: '0.00002~0.5'
  area_perimeter_rarange: '0.0005~0.1'
  bubble_px_range: '80~1000000'
  letter_px_range: '3~1000000'
  bubble_px_rarange: '0.3~0.99'
  letter_px_rarange: '0.008~0.7'
  BnL_px_rarange: '0.5~1.1'
  CTD_mask_px_rarange: '0.008~0.8'
#   CTD_thres: 127
  CTD_thres: 30
  edge_px_count_range: '0~15'
  letter_area_range: '1~9000'
#   textblock_area_range: '200~3000000'
  textblock_area_range: '3~3000000'
  textblock_wrange: '20~1988'
  textblock_hrange: '20~1000'
  textblock_w_prange: '0~1'
#   textblock_w_prange: '0.7~1'
  textblock_h_prange: '0~1'
#   textblock_h_prange: '0.7~1'
  letter_cnts_range: '1~1000'
  textblock_letters_range: '1~15000'
  note_area_range: '10~6000'
  max_note_dist: 5
#   intersect_ratio: 0.8
  intersect_ratio: 0.1
  seg_line_range: '50~500'
  angle_px_step: 2,15
  WBN_tolerance: 10,30,15
#   WBN_tolerance: 60,60,60
  textline_hrange: '6~40'
  line_multi_h: 25
  line_edge_range: '1~20'
  dot_line_h: 5
  dot_h: 4
  bulk_thres: 0
  overlap_ratio: 0.15
char_condition:
  px_area_range: '5~30000'
  cnt_area_range: '10~30000'
  thick_range: '4~4000'
  brw_range: '5~5000'
  brh_range: '5~7000'
bubble_recognize:
  # 用户设置的高度差异阈值
  max_height_diff: 28
  max_font_size: 150
  kernel_depth: 10
  block_ratio: 2
  bubble_alpha: 0.5
  bg_alpha: 0.5
  WLB_alpha: 30,50,30
  padding: 10
  r_dot: 5
#   rec_pad: 2
#   rec_pad: 5
  rec_pad: 10
#   rec_pad: 20
#   sum_sect_max: 5
  sum_sect_max: 9999
bubble_seg:
  use_rec: true
#   use_rec: false
#  use_dilate: true
  use_dilate: false
#  adapt_big_letter: true
  adapt_big_letter: false
#  check_note: true
  check_note: false
#  check_dots: true
  check_dots: false
  check_intact: true
#   check_intact: false
  use_pivot_split: true
#   use_pivot_split: false
#   sort_by_y: true
  sort_by_y: false
ocr_settings:
  discard_ratio: 0.08
#  y_thres: 8
  y_thres: 3
  min_char_area: 3
  min_cnt_area: 9
  bit_thres: 127
  white_thres: 200
#   white_thres: 250
  bi_thres: 127
#   bi_thres: 200
  ext_padding: 15
#   ext_padding: 90
  base_num: 5
#   base_num: 4
#  cal_method: 加权最小二乘法
#  cal_method: 非负最小二乘法
  cal_method: 加权非负最小二乘法
#   print_tables: true
  print_tables: false
  #init_ocr: true
  init_ocr: false
  use_textwords: true
#  use_textwords: false
  line_spacing: 20
  bubble_spacing: 50
  merge_update: true
#   merge_update: false
  all_caps: true
#  all_caps: false
  do_cap: true
#  do_cap: false
#   has_decoration: true
  has_decoration: false
  renew_stitch: true
#   renew_stitch: false
#   renew_CTD: true
  renew_CTD: false
#   CTD_cut: whole
#   CTD_cut: square
  CTD_cut: tile
  exclude_smaller: true
#   exclude_smaller: false
  exclude_inside: true
#   exclude_inside: false
#   ellipsis_type: '...'
  ellipsis_type: '…'
  #   use_sd: true
  use_sd: false
youdao:
  app_id:
  app_key:
caiyun:
  token: 3975l6lr5pcbvidl6jl2 # 公用
baidu:
  APP_ID:
  SECRET_KEY:
tencent:
  APPID:
  SecretId:
  SecretKey:
baidu_ocr:
  APP_ID:
  API_KEY:
  SECRET_KEY:
custom_ocr_engines:
#  - 'Baidu'
#  - 'BaiduAccu'
  - 'Paddle'
  - 'Easy'
prompt_prefix_dic:
  Comic: '您是一位专业的漫画翻译家，精通中文和英文。您的任务是翻译英文漫画，请把下列html翻译成中文，保留原格式，并以html格式输出。在翻译过程中，请仔细分析文本的上下文和情感色彩，确保翻译准确无误。人名和专有名词也要翻译成中文。翻译时要连贯、自然且符合中文表达习惯。翻译后的段落数量需和原文段落数量一致且一一对应，不能多段变成一段。'
  Manhua: '您是一位专业的漫画翻译家，精通中文和英文。您的任务是翻译中文漫画，请把下列html翻译成英文，保留原格式，并以html格式输出。在翻译过程中，请仔细分析文本的上下文和情感色彩，确保翻译准确无误。'
grid_ratio_dic:
  Comic: 0.90 # 美漫彩色
  Manhua: 0.90
  Manga: 0.90 # 日漫黑白
italic_color_locates:
#   - 'ffd266-ffface-000000'
#   - 'fbab3c-fff3e5-000000'
#   - 'e5f2c7-f1f5e4-000000'
#   - 'ccecc3-36b449'
#   - 'fdfdbd-000000'
#   - '0d0d0d-ffffff'
color_patterns:
#  - 'ffffff-15~9f2862-15' # 白底红字
#  - 'b9e6fb-15~000000-60' # 蓝底黑字
#  - 'fef7e5-15~000000-60' # 米底黑字
#  - 'ffffff-15~0799b0-60' # 白底蓝字
#  - 'e2e319-15~000000-60' # 绿底黑字
#  - '010101-15=667b8c-15~ffffff-60' # 黑灰底白字
#  - 'e5398b-15=50396d-15~ffffff-60' # 红紫底白字
color_pattern_dic:
  Comic:
    - 'ffffff-10~000000-60' # 白底黑字
#     - '000000-15~ffffff-60' # 黑底白字
#     - 'ffffff-10' # 白字
#     - '000000-60' # 黑字
  Manga:
#     - 'ffffff-15~000000-60' # 白底黑字
  Manhua:
#     - 'ffffff-15~000000-60' # 白底黑字